import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import { JSXElementConstructor, ReactElement, ReactFragment, ReactPortal, useEffect, useState } from 'react';
import styles from '../styles/Home.module.css';
import axios from 'axios'
import Menu from '../components/Menu';
import Footer from '../components/Footer';
import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';
import Lollipop from '../images/lollipop.png';
import Marshmallow from '../images/marshmallow.png';
const { ethers } = require("ethers");

const Home: NextPage = () => {
    
    const [blockNumber, setBlockNumber] = useState(0);

    const [ticking, setTicking] = useState(true);
    const [init, setInit] = useState(false);
    const [blockData, setBlockData] = useState<any>({});
   
   useEffect(() => {
    const blockLogic = async() => {
      const provider = new ethers.providers.AlchemyProvider('goerli', process.env.NEXT_PUBLIC_ALCHEMY_API_KEY);
      let blockN = await provider.getBlockNumber();
      
      setBlockNumber(blockN);
      setInit(true);
      let body = {blockNumber: blockNumber}
      }

    if (!init){

    blockLogic();
    }    

    const timer = setTimeout(() => {if (ticking){
      setBlockNumber(blockNumber+1);

    }}, 12000)
    return () => clearTimeout(timer)
   }, [blockNumber, ticking, init, blockData])




  return (
    <div className={styles.container}>
      <Head>
        <title className='main-text'>LolliBlocks</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
       
      </Head>

      <main className='container-fluid' >
      <Menu/>
      <div className='text-white pt-5 mt-5'>
        <h6 className="text-white">
          Block Explorer made with
          Ethers.js, Next.js and  PostgreSQL.<br/>
          Current block: <b>{blockNumber}</b>
          </h6>

        </div>
      <Container className='table'>


        <div id='titlecontainer'>
          <div className="text-white pt-3 mt-5 mb-5 pb-5">
            <div className='card  bg-transparent border-top border-bottom border-start-0 border-end-0 border-light border-5'>
            <h2 className={`${styles.title} main-text `}>LolliBlocks</h2>
            
            </div>
            
        </div> 
        </div>

        <div id="carouselExampleControls" className="carousel slide" data-bs-ride="carousel">
  <div className="carousel-inner">
    <div className="carousel-item active">
    <Col className='card mt-5 mx-3 card-css-t border-danger border-5 rounded-0'>
            <div className='card-header d-flex'>
            <h2 className='text-black mt-4 p-1 ml-3'>Last Transactions</h2>
            <Image 
        src={Marshmallow}
        width = {100}
        height = {100}
        alt=''
        />
            </div>
            <h4 className='mt-1 card-subtitle  text-muted'>Account monitoring</h4>
            
            <div className='card-body'>
            <h4 className='text-danger'>ERC-20</h4>
            <h4 className='text-danger'>ERC-721</h4>
            <h4 className='text-danger'>ERC-1155</h4>
            <h4 className='text-danger'>Votes</h4>
            
            </div>
          </Col>
    </div>
    <div className="carousel-item">
    <Col className='card mt-5 mx-3 card-css-t border-danger border-5 rounded-0'>
            <div className='card-header d-flex'>
            <h2 className='text-black mt-4 p-1 ml-3'>Last Transactions</h2>
            <Image 
        src={Marshmallow}
        width = {100}
        height = {100}
        alt=''
        />
            </div>
            <h4 className='mt-1 card-subtitle  text-muted'>Account monitoring</h4>
            
            <div className='card-body'>
            <h4 className='text-danger'>ERC-20</h4>
            <h4 className='text-danger'>ERC-721</h4>
            <h4 className='text-danger'>ERC-1155</h4>
            <h4 className='text-danger'>Votes</h4>
            
            </div>
          </Col>
    </div>
    <div className="carousel-item">
    <Col className='card mt-5 mx-3 card-css-t border-danger border-5 rounded-0'>
            <div className='card-header d-flex'>
            <h2 className='text-black mt-4 p-1 ml-3'>Last Transactions</h2>
            <Image 
        src={Marshmallow}
        width = {100}
        height = {100}
        alt=''
        />
            </div>
            <h4 className='mt-1 card-subtitle  text-muted'>Account monitoring</h4>
            
            <div className='card-body'>
            <h4 className='text-danger'>ERC-20</h4>
            <h4 className='text-danger'>ERC-721</h4>
            <h4 className='text-danger'>ERC-1155</h4>
            <h4 className='text-danger'>Votes</h4>
            
            </div>
          </Col>
    </div>
  </div>
  <button className="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
    <span className="carousel-control-prev-icon" aria-hidden="true"></span>
    <span className="visually-hidden">Previous</span>
  </button>
  <button className="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
    <span className="carousel-control-next-icon" aria-hidden="true"></span>
    <span className="visually-hidden">Next</span>
  </button>
</div>
        
        <Row className="text-secondary mt-5 pt-5 mb-5 ">
          
        <Col className='card mt-5 mx-3 card-css-t border-danger border-5 rounded-0'>
            <div className='card-header d-flex'>
            <h2 className='text-black mt-4 p-1 ml-3'>Last Transactions</h2>
            <Image 
        src={Marshmallow}
        width = {100}
        height = {100}
        alt=''
        />
            </div>
            <h4 className='mt-1 card-subtitle  text-muted'>Account monitoring</h4>
            
            <div className='card-body'>
            <h4 className='text-danger'>ERC-20</h4>
            <h4 className='text-danger'>ERC-721</h4>
            <h4 className='text-danger'>ERC-1155</h4>
            <h4 className='text-danger'>Votes</h4>
            
            </div>
          </Col>
          <Col className='card mt-5 mx-3 card-css-t border-danger border-5 rounded-0'>
          <div className='card-header d-flex'>
            <h2 className='text-black mt-4 p-1 ml-3'>Snapshots</h2>
            <Image 
        src={Lollipop}
        width = {100}
        height = {100}
        alt=''
        />
            </div>
            <h4 className='mt-1 card-subtitle text-muted'>Governance tools</h4>
            
            <div className='card-body'>
            <h4 className='text-primary'>ERC-20</h4>
            <h4 className='text-warning'>ERC-721</h4>
            <h4 className='text-success'>ERC-1155</h4>
            <h4 className='text-danger'>Votes</h4>
            </div>
          </Col>
        </Row>
       
        
        
</Container>
      </main>

      <Footer/>
    </div>
  );
};

export default Home;
