import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { JSXElementConstructor, ReactElement, ReactFragment, ReactPortal, useEffect, useState } from 'react';
import styles from '../styles/Home.module.css';
import axios from 'axios'
import Menu from '../components/Menu';
const { ethers } = require("ethers");

const Home: NextPage = () => {
    
    const [blockNumber, setBlockNumber] = useState(0);

    const [ticking, setTicking] = useState(true);
    const [init, setInit] = useState(false);
    const [blockData, setBlockData] = useState<any>({});
   
   useEffect(() => {
    const blockLogic = async() => {
      const provider = new ethers.providers.AlchemyProvider('goerli', process.env.NEXT_PUBLIC_ALCHEMY_API_KEY);
      let blockN = await provider.getBlockNumber();
      
      setBlockNumber(blockN);
      setInit(true);
      let body = {blockNumber: blockNumber}
      }

    if (!init){

    blockLogic();
    }    

    const timer = setTimeout(() => {if (ticking){
      setBlockNumber(blockNumber+1);
      
      let body = {blockNumber: blockNumber}
      axios.post('api/transactions', { data: body})
      .then(function (response){
        
        setBlockData(response)
        console.log(blockData)
        
      })
      .catch(function (error){
        console.log(error)
      })

    }}, 12000)
    return () => clearTimeout(timer)
   }, [blockNumber, ticking, init, blockData])




  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='container-fluid' >
      <Menu/>
        
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" target="_blank" rel="noopener noreferrer">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};

export default Home;
